#ifndef X_VIEW_BLOB_H
#define X_VIEW_BLOB_H

#include <opencvblobslib/blob.h>

namespace x_view {

/**
* \brief A Blob contains all pixels belonging to a connected component
* determined by their class labels.
*/
class Blob {

 public:
  Blob();
  Blob(const int semantic_label, const CBlob& c_blob);

  /// \brief Semantic label associated to all pixels contained in this blob.
  int semantic_label_;

  /// \brief Vector of pixels representing the contour of this blob.
  std::vector<cv::Point> external_contour_pixels_;
  std::vector<std::vector<cv::Point>> internal_contour_pixels_;

  /// \brief Number of pixels in this blob.
  int size_;

  /// \brief Pixel representing the center of the blob.
  cv::Point center_;

  /// \brief Returns the ellipse associated to the blob.
  CvBox2D ellipse() { return c_blob_.GetEllipse(); }

 private:
  /// \brief Object generated by the opencvblobslib containing data used to
  /// execute the functions provided by this struct.
  CBlob c_blob_;

  /// \brief Fits the contour pixels and extracts geometrical properties.
  void computeContours();

  /// \brief computes the number of pixels belonging to the blob.
  void computeArea() { size_ = c_blob_.Area(AreaMode::PIXELWISE); }

  /// \brief computes the center pixel of the blob.
  void computeCenter() { center_ = c_blob_.getCenter(); }

};

}

#endif //X_VIEW_BLOB_H
