#ifndef X_VIEW_X_VIEW_SEMANTICS_H
#define X_VIEW_X_VIEW_SEMANTICS_H

#include <x-view_core/types.h>

#include <opencv2/core/core.hpp>

#include <memory>

namespace x_view {
    /**
     * \brief object generated by matching two semantic landmarks
     */
    struct XViewSemanticMatchingResult {
        double score_;
    };

    /**
     * \brief Internal representation of a semantic landmark
     * \note The effective implementation of a semantic landmark might be a subclass of XViewSemantics
     */
    struct XViewSemantics {

        XViewSemantics(){}

        /**
         * \brief Semantic representation of viewed image is build from the instantiated class
         * \param image image containing semantic segmentation
         * \param pose 3D pose of the robot
         */
        XViewSemantics(const cv::Mat &image, const SE3 &pose);

        virtual ~XViewSemantics() {};

        /// \brief Robot's pose associated to this semantic landmark
        SE3 pose_;

        /// \brief Imge given as input for the landmark
        cv::Mat image_;

        /**
         * \brief Computes matching score between this and other semantic landmark
         * \param other other landmark to be compared to this
         * \return struct containing matching results
         */
        virtual XViewSemanticMatchingResult match(const XViewSemantics& other) = 0;


    }; // struct XViewSemantics

}
#endif //X_VIEW_X_VIEW_SEMANTICS_H
