#ifndef X_VIEW_ABSTRACT_SEMANTIC_LANDMARK_H
#define X_VIEW_ABSTRACT_SEMANTIC_LANDMARK_H

#include <x-view_core/x-view_types.h>

#include <opencv2/core/core.hpp>

#include <memory>

namespace x_view {
    /**
     * \brief object generated by matching two semantic landmarks
     */
    struct SemanticMatchingResult {
        double score_;
    };

    /**
     * \brief Internal representation of a semantic landmark
     * \note The effective implementation of a semantic landmark might be a subclass of XViewSemantics
     */
    struct AbstractSemanticLandmark {

        AbstractSemanticLandmark(){}

        /**
         * \brief Semantic representation of viewed image is build from the instantiated class
         * \param image image containing semantic segmentation
         * \param pose 3D pose of the robot
         */
        AbstractSemanticLandmark(const cv::Mat &image, const SE3 &pose);

        virtual ~AbstractSemanticLandmark() {};

        /// \brief Robot's pose associated to this semantic landmark
        SE3 pose_;

        /// \brief Image given as input for the landmark
        cv::Mat image_;

        /**
         * \brief Computes matching score between this and other semantic landmark
         * \param other other landmark to be compared to this
         * \return struct containing matching results
         */
        virtual SemanticMatchingResult match(const AbstractSemanticLandmark& other) = 0;


    }; // struct AbstractSemanticLandmark

}
#endif //X_VIEW_ABSTRACT_SEMANTIC_LANDMARK_H
