#include <x_view_core/features/graph.h>
#include <x_view_core/landmarks/graph_landmark/random_walker.h>

#ifndef X_VIEW_TEST_RANDOM_WALK_H
#define X_VIEW_TEST_RANDOM_WALK_H

/**
 * \brief Generates a random graph with num_vertices vertices, where each
 * pair of vertices is linked by an edge with probability edge_probability. A
 * random semantic class is associated to each vertex of the graph.
 * \param num_vertices Number of vertices of the generated graph.
 * \param edge_probability Probability to generate an edge between each pair
 * of vertices.
 * \param num_semantic_classes Number of semantic classes. Each vertex is
 * associated to a random semantic class (random integer in {0, ..,
 * num_semantic_classes-1}
 * \return The randomly generated graph.
 */
x_view::Graph::GraphType generateRandomGraph(const int num_vertices,
                                             const float edge_probability,
                                             const int num_semantic_classes);


/**
 * \brief Tests the transition probability matrix generated by the
 * RandomWalker class. The transition probability matrix is tested by
 * counting how many non-zero elements it contains and on the non-zero
 * elements values.
 * \param graph Graph to be tested.
 * \param params Parameters to be used by the RandomWalker class to generate
 * the transition probability matrix.
 */
void testTransitionProbabilityMatrix(const x_view::Graph::GraphType graph,
                                     const x_view::RandomWalkerParams& params);

#endif //PROJECT_TEST_RANDOM_WALK_H
